name: Build
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  build-action:
    name: Build Action
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        runner: [blacksmith, blacksmith-arm]
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Check Formatting
        run: pnpm prettier --check .

      - name: Check Lint
        run: pnpm eslint

      - name: Check Types
        run: pnpm tsc

      - name: Test Action
        run: pnpm test

      - name: Build Action
        run: pnpm rollup -c && git diff --exit-code dist
